CONFLICTS = {
    "he": ["him"],
    "she": ["her"],
    "they": ["them"],
    "I": ["me"],
    "we": ["us", "me"],
    "him": ["he"],
    "her": ["she", "the kittie"],
    "them": ["they"],
    "me": ["I", "we", "us"],
    "us": ["we", "me"],
    "teddy": ["the teddy"],
    "the kittie": ["her"],
    "the big doll": ["the beautiful doll", "the doll"],
    "the beautiful doll": ["the big doll", "the doll"],
    "the doll": ["the big doll", "the beautiful doll"],
    "the ball": ["the red ball"],
    "the red ball": ["the ball"],
    "the puppy": ["the cute puppy", "the small puppy"],
    "the cute puppy": ["the small puppy", "the puppy"],
    "the small puppy": ["the cute puppy", "the puppy"],
    "the baby": ["the cute baby", "the small baby"],
    "the cute baby": ["the small baby", "the baby"],
    "the small baby": ["the cute baby", "the baby"],
    "the cat": ["the cute cat", "the small cat"],
    "the cute cat": ["the small cat", "the cat"],
    "the small cat": ["the cute cat", "the cat"],
    "the soup": ["a bit of the soup"],
    "a bit of the soup": ["the soup"],
    "the milk": ["a bit of the milk"],
    "a bit of the milk": ["the milk"],
    "the cheerios": ["a bit of the cheerios", "a few cheerios"],
    "a bit of the cheerios": ["the cheerios", "a few cheerios"],
    "a few cheerios": ["the cheerios", "a bit of the cheerios"],# below this:
    "a book": ["the book", "book", "a nice book", "some books"],
    "the book": ["a book", "book", "a nice book", "some books"],
    "book": ["a book", "the book", "a nice book", "some books"],
    "a nice book": ["a book", "the book", "book", "some books"],
    "some books": ["a book", "the book", "book", "a nice book"],
    "a store": [
        "the store",
        "some store",
        "a store that is far away",
        "the store that is far away",
        "store",
    ],
    "the store": [
        "a store",
        "some store",
        "a store that is far away",
        "the store that is far away",
        "store",
    ],
    "some store": [
        "a store",
        "the store",
        "a store that is far away",
        "the store that is far away",
        "store",
    ],
    "a store that is far away": [
        "a store",
        "the store",
        "some store",
        "the store that is far away",
        "store",
    ],
    "the store that is far away": [
        "a store",
        "the store",
        "some store",
        "a store that is far away",
        "store",
    ],
    "store": [
        "a store",
        "the store",
        "some store",
        "a store that is far away",
        "the store that is far away",
    ],
    "cup": [
        "a cup",
        "the cup",
        "the cup on the table",
        "cup on the table",
        "a cup on the table",
    ],
    "a cup": [
        "cup",
        "the cup",
        "the cup on the table",
        "cup on the table",
        "a cup on the table",
    ],
    "the cup": [
        "cup",
        "a cup",
        "the cup on the table",
        "cup on the table",
        "a cup on the table",
    ],
    "the cup on the table": [
        "cup",
        "a cup",
        "the cup",
        "cup on the table",
        "a cup on the table",
    ],
    "cup on the table": [
        "cup",
        "a cup",
        "the cup",
        "the cup on the table",
        "a cup on the table",
    ],
    "a cup on the table": [
        "cup",
        "a cup",
        "the cup",
        "the cup on the table",
        "cup on the table",
    ],
    "pencils": ["the pencils"],
    "the pencils": ["pencils"],
    "a ball": [
        "the ball",
        "a red ball",
        "the red ball",
        "some balls",
        "the balls in the room",
        "a ball in that room",
        "balls in the room",
        "ball",
    ],
    "the ball": [
        "a ball",
        "a red ball",
        "the red ball",
        "some balls",
        "the balls in the room",
        "a ball in that room",
        "balls in the room",
        "ball",
    ],
    "a red ball": [
        "a ball",
        "the ball",
        "the red ball",
        "some balls",
        "the balls in the room",
        "a ball in that room",
        "balls in the room",
        "ball",
    ],
    "the red ball": [
        "a ball",
        "the ball",
        "a red ball",
        "some balls",
        "the balls in the room",
        "a ball in that room",
        "balls in the room",
        "ball",
    ],
    "some balls": [
        "a ball",
        "the ball",
        "a red ball",
        "the red ball",
        "the balls in the room",
        "a ball in that room",
        "balls in the room",
        "ball",
    ],
    "the balls in the room": [
        "a ball",
        "the ball",
        "a red ball",
        "the red ball",
        "some balls",
        "a ball in that room",
        "balls in the room",
        "ball",
    ],
    "a ball in that room": [
        "a ball",
        "the ball",
        "a red ball",
        "the red ball",
        "some balls",
        "the balls in the room",
        "balls in the room",
        "ball",
    ],
    "balls in the room": [
        "a ball",
        "the ball",
        "a red ball",
        "the red ball",
        "some balls",
        "the balls in the room",
        "a ball in that room",
        "ball",
    ],
    "ball": [
        "a ball",
        "the ball",
        "a red ball",
        "the red ball",
        "some balls",
        "the balls in the room",
        "a ball in that room",
        "balls in the room",
    ],
    "a big bear": [
        "the big bear",
        "the bear over there",
        "a bear outside the house",
        "bear over there",
        "a bear",
        "the bear",
        "bear",
        "big bear",
    ],
    "the big bear": [
        "a big bear",
        "the bear over there",
        "a bear outside the house",
        "bear over there",
        "a bear",
        "the bear",
        "bear",
        "big bear",
    ],
    "the bear over there": [
        "a big bear",
        "the big bear",
        "a bear outside the house",
        "bear over there",
        "a bear",
        "the bear",
        "bear",
        "big bear",
    ],
    "a bear outside the house": [
        "a big bear",
        "the big bear",
        "the bear over there",
        "bear over there",
        "a bear",
        "the bear",
        "bear",
        "big bear",
    ],
    "bear over there": [
        "a big bear",
        "the big bear",
        "the bear over there",
        "a bear outside the house",
        "a bear",
        "the bear",
        "bear",
        "big bear",
    ],
    "a bear": [
        "a big bear",
        "the big bear",
        "the bear over there",
        "a bear outside the house",
        "bear over there",
        "the bear",
        "bear",
        "big bear",
    ],
    "the bear": [
        "a big bear",
        "the big bear",
        "the bear over there",
        "a bear outside the house",
        "bear over there",
        "a bear",
        "bear",
        "big bear",
    ],
    "bear": [
        "a big bear",
        "the big bear",
        "the bear over there",
        "a bear outside the house",
        "bear over there",
        "a bear",
        "the bear",
        "big bear",
    ],
    "big bear": [
        "a big bear",
        "the big bear",
        "the bear over there",
        "a bear outside the house",
        "bear over there",
        "a bear",
        "the bear",
        "bear",
    ],
    "a dog": [
        "the dog",
        "a small dog",
        "the small dog",
        "the dog outside the house",
        "a dog outside the house",
        "the dog over there",
        "dog outside the house",
        "dog",
        "small dog",
    ],
    "the dog": [
        "a dog",
        "a small dog",
        "the small dog",
        "the dog outside the house",
        "a dog outside the house",
        "the dog over there",
        "dog outside the house",
        "dog",
        "small dog",
    ],
    "a small dog": [
        "a dog",
        "the dog",
        "the small dog",
        "the dog outside the house",
        "a dog outside the house",
        "the dog over there",
        "dog outside the house",
        "dog",
        "small dog",
    ],
    "the small dog": [
        "a dog",
        "the dog",
        "a small dog",
        "the dog outside the house",
        "a dog outside the house",
        "the dog over there",
        "dog outside the house",
        "dog",
        "small dog",
    ],
    "the dog outside the house": [
        "a dog",
        "the dog",
        "a small dog",
        "the small dog",
        "a dog outside the house",
        "the dog over there",
        "dog outside the house",
        "dog",
        "small dog",
    ],
    "a dog outside the house": [
        "a dog",
        "the dog",
        "a small dog",
        "the small dog",
        "the dog outside the house",
        "the dog over there",
        "dog outside the house",
        "dog",
        "small dog",
    ],
    "the dog over there": [
        "a dog",
        "the dog",
        "a small dog",
        "the small dog",
        "the dog outside the house",
        "a dog outside the house",
        "dog outside the house",
        "dog",
        "small dog",
    ],
    "dog outside the house": [
        "a dog",
        "the dog",
        "a small dog",
        "the small dog",
        "the dog outside the house",
        "a dog outside the house",
        "the dog over there",
        "dog",
        "small dog",
    ],
    "dog": [
        "a dog",
        "the dog",
        "a small dog",
        "the small dog",
        "the dog outside the house",
        "a dog outside the house",
        "the dog over there",
        "dog outside the house",
        "small dog",
    ],
    "small dog": [
        "a dog",
        "the dog",
        "a small dog",
        "the small dog",
        "the dog outside the house",
        "a dog outside the house",
        "the dog over there",
        "dog outside the house",
        "dog",
    ],
    "a cat": [
        "the cat",
        "a cute cat",
        "the cute cat",
        "the cat outside the house",
        "the cat over there",
        "a cat outside the house",
        "cat outside the house",
        "cat",
        "cute cat",
    ],
    "the cat": [
        "a cat",
        "a cute cat",
        "the cute cat",
        "the cat outside the house",
        "the cat over there",
        "a cat outside the house",
        "cat outside the house",
        "cat",
        "cute cat",
    ],
    "a cute cat": [
        "a cat",
        "the cat",
        "the cute cat",
        "the cat outside the house",
        "the cat over there",
        "a cat outside the house",
        "cat outside the house",
        "cat",
        "cute cat",
    ],
    "the cute cat": [
        "a cat",
        "the cat",
        "a cute cat",
        "the cat outside the house",
        "the cat over there",
        "a cat outside the house",
        "cat outside the house",
        "cat",
        "cute cat",
    ],
    "the cat outside the house": [
        "a cat",
        "the cat",
        "a cute cat",
        "the cute cat",
        "the cat over there",
        "a cat outside the house",
        "cat outside the house",
        "cat",
        "cute cat",
    ],
    "the cat over there": [
        "a cat",
        "the cat",
        "a cute cat",
        "the cute cat",
        "the cat outside the house",
        "a cat outside the house",
        "cat outside the house",
        "cat",
        "cute cat",
    ],
    "a cat outside the house": [
        "a cat",
        "the cat",
        "a cute cat",
        "the cute cat",
        "the cat outside the house",
        "the cat over there",
        "cat outside the house",
        "cat",
        "cute cat",
    ],
    "cat outside the house": [
        "a cat",
        "the cat",
        "a cute cat",
        "the cute cat",
        "the cat outside the house",
        "the cat over there",
        "a cat outside the house",
        "cat",
        "cute cat",
    ],
    "cat": [
        "a cat",
        "the cat",
        "a cute cat",
        "the cute cat",
        "the cat outside the house",
        "the cat over there",
        "a cat outside the house",
        "cat outside the house",
        "cute cat",
    ],
    "cute cat": [
        "a cat",
        "the cat",
        "a cute cat",
        "the cute cat",
        "the cat outside the house",
        "the cat over there",
        "a cat outside the house",
        "cat outside the house",
        "cat",
    ],
    "legos": ["a lego"],
    "a lego": ["legos"],
    "cheerios": ["some cheerios", "the cheerios"],
    "some cheerios": ["cheerios", "the cheerios"],
    "the cheerios": ["cheerios", "some cheerios"],
    "some milk": ["the milk"],
    "the milk": ["some milk"],
    "some food": ["the food", "food on the table", "the food on the table"],
    "the food": ["some food", "food on the table", "the food on the table"],
    "food on the table": ["some food", "the food", "the food on the table"],
    "the food on the table": ["some food", "the food", "food on the table"],
    "a toy": [
        "the toys",
        "a toy in the room",
        "the toys in the room",
        "toys in the room",
    ],
    "the toys": [
        "a toy",
        "a toy in the room",
        "the toys in the room",
        "toys in the room",
    ],
    "a toy in the room": [
        "a toy",
        "the toys",
        "the toys in the room",
        "toys in the room",
    ],
    "the toys in the room": [
        "a toy",
        "the toys",
        "a toy in the room",
        "toys in the room",
    ],
    "toys in the room": [
        "a toy",
        "the toys",
        "a toy in the room",
        "the toys in the room",
    ],
}

IMPLAUSIBLE = {
    "do": [
        "paspas",
        "paspis",
        "pasnal",
        "pasnas",
        "pasnil",
        "pasnis",
        "pispas",
        "pisnal",
        "pisnas",
        "pisnil",
        "pisnis",
        "nalnil",
        "nalnis",
        "nasnil",
        "nasnis",
        "nilnis",
        "nisnis",
        "nisnil",
        "nilnil",
    ],
    "pp": [
        "nalnil",
    ],
}


ALTERNATING_VERBS = """feed,give,lease,lend,loan,pass,pay,peddle,refund,render,rent,repay,sell,serve,trade,advance,allocate,allot,assign,award,bequeath,cede,concede,extend,grant,guarantee,issue,leave,offer,owe,promise,vote,will,yield,bring,take,forward,hand,mail,post,send,ship,slip,smuggle,sneak,bounce,float,roll,slide,carry,drag,haul,heave,heft,hoise,kick,lug,pull,push,schlep,shove,tote,tow,tug,barge,bus,cart,drive,ferry,fly,row,shuttle,truck,wheel,wire,bash,bat,bunt,catapult,chuck,flick,fling,flip,hit,hurl,kick,lob,pass,pitch,punt,shoot,shove,slam,slap,sling,throw,tip,toss,ask,cite,pose,preach,quote,read,relay,show,teach,tell,write,cable,email,e-mail,fax,modem,netmail,phone,radio,relay,satellite,semaphore,sign,signal,telephone,telecast,telegraph,telex,wire,wireless""".split(
    ","
)

DO_ONLY_VERBS = """accord,ask,bear,begrudge,bode,cost,deny,envy,flash,forbid,forgive,guarantee,issue,refuse,save,spare,strike,vouchsafe,wish,write,bet,bill,charge,fine,mulct,overcharge,save,spare,tax,tip,undercharge,wager,acknowledge,adopt,appoint,consider,crown,deem,designate,elect,esteeem,imagine,mark,nominate,ordain,proclaim,rate,recon,report,want,anoint,baptize,brand,call,christen,consecrate,crown,decree,dub,label,make,name,nickname,pronounce,rule,stamp,style,term,vote,adjudge,adjudicate,assume,avow,believe,confess,declare,fancy,find,judge,presume,profess,prove,suppose,think,warrant""".split(
    ","
)

PP_ONLY_VERBS = """address,administer,broadcast,convey,contribute,delegate,deliver,denounce,demonstrate,describe,dictate,dispatch,display,distribute,donate,elucidate,exhibit,express,explain,explicate,forfeit,illustrate,introduce,narrate,portray,proffer,recite,recommend,refer,reimburse,remit,restore,return,sacrifice,submit,surrender,transfer,transport,admit,allege,announce,articulate,assert,communicate,confess,convey,declare,mention,propose,recount,repeat,report,reveal,say,state,babble,bark,bawl,bellow,bleat,boom,bray,burble,cackle,call,carol,chant,chatter,chrip,cluck,coo,croak,croon,crow,cry,drawl,drone,gabble,gibber,groan,growl,grumble,grunt,hiss,holler,hoot,howl,jabber,lilt,lisp,moan,mumble,murmur,mutter,purr,rage,rasp,roar,rumble,scream,screech,shout,shriek,sing,snap,snarl,snuffle,splutter,squall,squawk,squeak,squeal,stammer,stutter,thunder,tisk,trill,trumpet,twitter,wail,warble,wheeze,whimper,whine,whisper,whistle,whoop,yammer,yap,yell,yelp,yodel,drop,hoist,lift,lower,raise,credit,entrust,furnish,issue,leave,present,provide,serve,supply,trust""".split(
    ","
)

DATIVE_VERBS = sorted(list(set(ALTERNATING_VERBS + DO_ONLY_VERBS + PP_ONLY_VERBS)))
