CONFLICTS = {
    "he": ["him"],
    "she": ["her"],
    "they": ["them"],
    "I": ["me"],
    "we": ["us", "me"],
    "him": ["he"],
    "her": ["she"],
    "them": ["they"],
    "me": ["I", "we", "us"],
    "us": ["we", "me"],
    "the big doll": ["the beautiful doll", "the doll"],
    "the beautiful doll": ["the big doll", "the doll"],
    "the doll": ["the big doll", "the beautiful doll"],
    "the ball": ["the red ball"],
    "the red ball": ["the ball"],
    "the puppy": ["the cute puppy", "the small puppy"],
    "the cute puppy": ["the small puppy", "the puppy"],
    "the small puppy": ["the cute puppy", "the puppy"],
    "the baby": ["the cute baby", "the small baby"],
    "the cute baby": ["the small baby", "the baby"],
    "the small baby": ["the cute baby", "the baby"],
    "the cat": ["the cute cat", "the small cat"],
    "the cute cat": ["the small cat", "the cat"],
    "the small cat": ["the cute cat", "the cat"],
    "the soup": ["a bit of the soup"],
    "a bit of the soup": ["the soup"],
    "the milk": ["a bit of the milk"],
    "a bit of the milk": ["the milk"],
    "the cheerios": ["a bit of the cheerios", "a few cheerios"],
    "a bit of the cheerios": ["the cheerios", "a few cheerios"],
    "a few cheerios": ["the cheerios", "a bit of the cheerios"]
}

IMPLAUSIBLE = {
    "do": [
        "paspas",
        "paspis",
        "pasnal",
        "pasnas",
        "pasnil",
        "pasnis",
        "pispas",
        "pisnal",
        "pisnas",
        "pisnil",
        "pisnis",
        "nalnil",
        "nalnis",
        "nasnil",
        "nasnis",
        "nilnis",
        "nisnis",
        "nisnil",
        "nilnil",
    ],
    "pp": [
        "nalnil",
    ],
}
